force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Livro</description>
    <label>Livro</label>
    <nameField>
        <label>Nome do Livro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookCheckpoint__c/BookCheckpoint__c.object-meta.xml
<CustomObject>
    <label>Book Checkpoint</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CheckpointNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Checkpoints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookCheckpoint__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Book</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Book Checkpoints</relationshipLabel>
    <relationshipName>BookCheckpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookCheckpoint__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookLead__c/BookLead__c.object-meta.xml
<CustomObject>
    <label>Book Lead</label>
    <nameField>
        <label>Book Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookLead__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Book</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Book Leads</relationshipLabel>
    <relationshipName>BookLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/isAvailableToPublish__c.field-meta.xml
<CustomField>
    <fullName>isAvailableToPublish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is available to publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BookLead__c.field-meta.xml
<CustomField>
    <fullName>BookLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book Lead</label>
    <referenceTo>BookLead__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PageCount__c.field-meta.xml
<CustomField>
    <fullName>PageCount__c</fullName>
    <label>Page count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/classes/CreateGameController.cls
/**
 * @description       : 
 * @author            : douglas.marinho@globant.com
 * @group             : 
 * @last modified on  : 03-27-2024
 * @last modified by  : dglsmrnh
**/
public with sharing class CreateGameController {
    @AuraEnabled
    public static Boolean createGameMemory(String recordId, ShadifyAPI.MemoryGameResponse gameData, List<PairValues> images, List<String> checkpoints){
        
        try {
            if(gameData.totalPairs != images.size()) {
                throw new AuraHandledException('Não foram informadas todas as imagens.');
            }

            // if(checkpoints.isEmpty()) {
            //     throw new AuraHandledException('Não foram informados os checkpoints.');
            // }

            for(ShadifyAPI.PairPosition pair : gameData.pairPositions) {
                for(PairValues pairValue : images) {
                    if(pairValue.value == pair.value) {
                        pair.contentVersionId = pairValue.contentVersionId;
                    }
                }
            }

            BookLead__c bk = [SELECT Id, Book__c, isAvailableToPublish__c FROM BookLead__c WHERE Id =: recordId LIMIT 1];
            String jsonString = JSON.serialize(gameData);
            Games__c game = new Games__c();
            game.BookLead__c = bk.Id;
            game.Book__c = bk.Book__c;
            game.Payload__c = jsonString;
            game.Type__c = 'Memory';
            
            insert game;

            if(bk.isAvailableToPublish__c != true) {
                bk.isAvailableToPublish__c = true;
                update bk;
            }

            List<BookCheckpoint__c> bookCheckList = new List<BookCheckpoint__c>();

            for(String checkpoint : checkpoints) {
                BookCheckpoint__c bookCheck = new BookCheckpoint__c();
                bookCheck.Book__c = bk.Book__c;
                bookCheck.Page__c = Integer.valueOf(checkpoint);

                bookCheckList.add(bookCheck);
            }

            if(!bookCheckList.isEmpty()) {
                insert bookCheckList;
            }

            return true;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class PairValues {
        @AuraEnabled
        public String value {get;set;}
        @AuraEnabled
        public Boolean uploaded {get;set;}
        @AuraEnabled
        public String img {get;set;}
        @AuraEnabled
        public String contentVersionId {get;set;}
    }

    @AuraEnabled(cacheable=true)
    public static Product2 getProductData(String bookLeadId) {
        BookLead__c bk = [SELECT Id, Book__c FROM BookLead__c WHERE Id =: bookLeadId];
        Product2 product = [SELECT Id, PageCount__c FROM Product2 WHERE Id =: bk.Book__c];
        return product;
    }
}