force-app/main/default/objects/Account/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>Aniversário</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gênero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Senha usada pelo usuário</description>
    <label>Senha</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username used by the user to login</description>
    <externalId>true</externalId>
    <label>Nome de usuário</label>
    <length>31</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Livro</description>
    <label>Livro</label>
    <nameField>
        <label>Nome do Livro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookLead__c/BookLead__c.object-meta.xml
<CustomObject>
    <label>Book Lead</label>
    <nameField>
        <label>Book Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookLead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Professor, Parent</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Book Leads</relationshipLabel>
    <relationshipName>Book_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/ARI__c.field-meta.xml
<CustomField>
    <fullName>ARI__c</fullName>
    <label>Automated readability index (ARI)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Book</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Book Leads</relationshipLabel>
    <relationshipName>BookLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/BookExcerpt__c.field-meta.xml
<CustomField>
    <fullName>BookExcerpt__c</fullName>
    <label>Book excerpt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/ColemanLiau__c.field-meta.xml
<CustomField>
    <fullName>ColemanLiau__c</fullName>
    <label>Coleman-Liau index</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/Flesch__c.field-meta.xml
<CustomField>
    <fullName>Flesch__c</fullName>
    <label>Flesch reading ease</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/Gulpease__c.field-meta.xml
<CustomField>
    <fullName>Gulpease__c</fullName>
    <label>Indice Gulpease</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookLead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Closed - Converted</fullName>
            </value>
            <value>
                <fullName>Closed - Not Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BookLead__c.field-meta.xml
<CustomField>
    <fullName>BookLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book Lead</label>
    <referenceTo>BookLead__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ISBN_10__c.field-meta.xml
<CustomField>
    <fullName>ISBN_10__c</fullName>
    <externalId>true</externalId>
    <label>ISBN 10</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ISBN_13__c.field-meta.xml
<CustomField>
    <fullName>ISBN_13__c</fullName>
    <externalId>true</externalId>
    <label>ISBN 13</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/MaturityRating__c.field-meta.xml
<CustomField>
    <fullName>MaturityRating__c</fullName>
    <label>Maturity Rating</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PageCount__c.field-meta.xml
<CustomField>
    <fullName>PageCount__c</fullName>
    <label>Page count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PublishedDate__c.field-meta.xml
<CustomField>
    <fullName>PublishedDate__c</fullName>
    <label>Published date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <label>Publisher</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/classes/ApprovalScreenControllerTest.cls
/**
 * @description       : 
 * @author            : douglas.marinho@globant.com
 * @group             : 
 * @last modified on  : 02-29-2024
 * @last modified by  : douglas.marinho@globant.com
**/
@IsTest
private with sharing class ApprovalScreenControllerTest {
	@TestSetup
	static void makeData() {
		// Create test data for the account
        Account newAccount = new Account(
            Name = 'Test Account',
            Email__c = 'test@example.com',
            Username__c = 'testuser',
            Password__c = 'Password@123',
            Gender__c = 'Male',
            Birthday__c = Date.newInstance(2000, 1, 1),
            Type = 'Professor'
        );
        insert newAccount;

        Product2 prod = new Product2(
			IsActive = false,
            Name = 'Test Book',
            ISBN_10__c = '1234567890123',
            ISBN_13__c = '0123456789',
            MaturityRating__c = 'Mature',
            Author__c = 'Test Author',
            PageCount__c = 200,
            Family = 'Book',
            RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Book').getRecordTypeId(),
            DisplayUrl = 'http://example.com/thumbnail.jpg',
            Description = 'Test description',
            PublishedDate__c = Date.Today(),
            Publisher__c = 'Test Publisher'
		);
        insert prod;

		BookLead__c bk = new BookLead__c();
            bk.Book__c = prod.Id;
            bk.Name = 'Test Book';
            bk.Account__c = newAccount.Id;
            bk.ARI__c = 10;
            bk.Score__c = 20;
            bk.Flesch__c = 30;
            bk.Gulpease__c = 40;
            bk.ColemanLiau__c = 50;
            bk.Status__c = 'Open';
            bk.BookExcerpt__c = 'Test description';
		insert bk;

		String approvalProcessName = '';
		for (ProcessDefinition retrievedProcess : getProcessDefinitionsBySObject('BookLead__c')) {
			approvalProcessName = 'ReadingApproval';
		}

		if (!String.isBlank(approvalProcessName)) {
			Approval.ProcessSubmitRequest newApprovalProcess = new Approval.ProcessSubmitRequest();
			newApprovalProcess.setComments('Class Test');
			newApprovalProcess.setObjectId(bk.Id);
			newApprovalProcess.setSubmitterId(UserInfo.getUserId());
			newApprovalProcess.setNextApproverIds(new List<String>{ UserInfo.getUserId() });
			newApprovalProcess.setProcessDefinitionNameOrId(approvalProcessName);
			newApprovalProcess.setSkipEntryCriteria(true);

			Approval.process(newApprovalProcess);
		}
	}

	@IsTest
	static void getComponentDataTest() {
		ApprovalScreenController.PicklistData picklist = new ApprovalScreenController.PicklistData();
		ApprovalScreenController.ComponentData componentData = new ApprovalScreenController.ComponentData('Error');
		componentData = new ApprovalScreenController.ComponentData(
			new ApprovalScreenController.CustomException()
		);

		componentData = ApprovalScreenController.getComponentData();
		// System.assertEquals(1, componentData.recordDataMap.size());
	}

	@IsTest
	static void searchProcessesTest() {
		User currentUser = getUserById(UserInfo.getUserId());
		String approvalProcessName = '';

		for (ProcessDefinition retrievedProcess : getProcessDefinitionsBySObject('BookLead__c')) {
			approvalProcessName = retrievedProcess.DeveloperName;
		}

		ApprovalScreenController.FilterData filter = new ApprovalScreenController.FilterData();
		filter.objectSelectedList = new List<String>{ 'BookLead__c' };
		filter.statusSelectedList = new List<String>{ 'Pending' };
		filter.processSelectedList = new List<String>{ approvalProcessName };
		filter.approverName = currentUser.Name;
		filter.submitterName = currentUser.Name;

		Map<String, ApprovalScreenController.RecordData> recordDataMap = ApprovalScreenController.searchProcesses(
			filter, 30
		);
		recordDataMap = ApprovalScreenController.searchProcesses(null, 30);
		// System.assertEquals(true, recordDataMap.isEmpty());
	}

	@IsTest
	static void approvalRecordsTest() {
		ApprovalScreenController.ComponentData componentData = ApprovalScreenController.getComponentData();
		// System.assertEquals(1, componentData.recordDataMap.size());

		ApprovalScreenController.ApprovalResponse approvalResponse = new ApprovalScreenController.ApprovalResponse(
			'Error', false
		);
		List<ApprovalScreenController.ApprovalResponse> approvalList = ApprovalScreenController.approvalRecords(
			componentData.recordDataMap,
			true
		);
		for (ApprovalScreenController.ApprovalResponse retrievedApproval : approvalList) {
			// System.assertEquals(true, retrievedApproval.isSuccess);
		}

		approvalList = ApprovalScreenController.approvalRecords(null, true);
		for (ApprovalScreenController.ApprovalResponse retrievedApproval : approvalList) {
			// System.assertEquals(true, retrievedApproval.hasError);
		}
	}

	@IsTest
	static void checkProcessHistoryTest() {
		ApprovalScreenController.RecordData recordData = new ApprovalScreenController.RecordData();
		ApprovalScreenController.ComponentData componentData = ApprovalScreenController.getComponentData();
		// System.assertEquals(1, componentData.recordDataMap.size());

		String recordId;
		for (String retrievedId : componentData.recordDataMap.keySet()) {
			recordData = componentData.recordDataMap.get(retrievedId);
			recordId = recordData.recordId;
		}

		List<ApprovalScreenController.RecordData> recordDataList = ApprovalScreenController.checkProcessHistory(recordId);
		// System.assertEquals(2, recordDataList.size());
	}

	static User getUserById(Id userId) {
		User currentUser;

		for (User retrievedUser : [
			SELECT Id, Name
			  FROM User
			 WHERE Id = :userId
			 LIMIT 1
		]) {
			currentUser = retrievedUser;
		}

		return currentUser;
	}

	static List<ProcessDefinition> getProcessDefinitionsBySObject(String sobjectName) {
		return [
			SELECT Id, DeveloperName
			  FROM ProcessDefinition
			 WHERE State = 'Active'
			   AND TableEnumOrId = :sobjectName
			 ORDER BY DeveloperName
			 LIMIT 1
		];
	}
}