force-app/main/default/objects/Account/fields/DefaultClass__c.field-meta.xml
<CustomField>
    <fullName>DefaultClass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Class</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.RecordType.Name</field>
            <operation>equals</operation>
            <value>Class</value>
        </filterItems>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>AccountClasses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username used by the user to login</description>
    <externalId>true</externalId>
    <label>Nome de usuário</label>
    <length>31</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/InitialClass__mdt/InitialClass__mdt.object-meta.xml
<CustomObject>
    <label>Initial Class</label>
    <pluralLabel>Initial Classes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Objeto que pertence a um personagem, que contém seus itens.</description>
    <label>Inventário</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventários</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Conta a quem pertence este inventário.</description>
    <inlineHelpText>Conta a quem pertence este inventário.</inlineHelpText>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inventorys</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Coins__c.field-meta.xml
<CustomField>
    <fullName>Coins__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Moedas</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InventoryItem__c/InventoryItem__c.object-meta.xml
<CustomObject>
    <label>Item do Inventário</label>
    <nameField>
        <label>Item do Inventário Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do Inventário</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryItem__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Cor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InventoryItem__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <description>Inventário do item</description>
    <label>Inventário</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Itens do Inventário</relationshipLabel>
    <relationshipName>InventoryItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InventoryItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantidade deste item no inventário.</description>
    <label>Quantidade</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Potion__mdt/Potion__mdt.object-meta.xml
<CustomObject>
    <description>Dados das poções utilizadas pelo personagem do usuário</description>
    <label>Poção</label>
    <pluralLabel>Poções</pluralLabel>
</CustomObject>

force-app/main/default/objects/Potion__mdt/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Cor da poção selecionada</description>
    <label>Cor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yellow</fullName>
                <default>true</default>
                <label>Yellow</label>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/classes/AccountHelper.cls
/**
 * @description       : 
 * @author            : dglsmrnh
 * @group             : 
 * @last modified on  : 02-25-2024
 * @last modified by  : dglsmrnh
**/
public without sharing class AccountHelper {
    
    public static final Id PRODUCT_CLASS_RECORDTYPE = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Class').getRecordTypeId();
    public static final Id ASSET_CLASS_RECORDTYPE = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Class').getRecordTypeId();

    public static void createDefaultClass(Map<Id, Account> newMap) {
        Map<String, String> classMap = new Map<String, String>();
        for(Account account : newMap.values()) {
            if(String.isEmpty(account.Type)) {
                account.Type = 'Child';
            }
            InitialClass__mdt initialClass = InitialClass__mdt.getInstance(account.Type);
            classMap.put(account.Type, initialClass.MasterLabel);            
        }

        List<Product2> productList = [SELECT Id, Name FROM Product2 WHERE Name IN: classMap.values() AND RecordTypeId =: PRODUCT_CLASS_RECORDTYPE];
        Map<String, Id> productMap = new Map<String, Id>();
        for(Product2 product : productList) {
            productMap.put(product.Name, product.Id);
        }

        List<Asset> assetList = new List<Asset>();
        for(Account account : newMap.values()) {
            if(classMap.containsKey(account.Type)) {
                String className = classMap.get(account.Type);
                if(productMap.containsKey(className)) {
                    Asset asset = new Asset();
                    asset.AccountId = account.Id;
                    asset.RecordTypeId = ASSET_CLASS_RECORDTYPE;
                    asset.Product2Id = productMap.get(className);
                    asset.Name = className;
                    asset.ExternalId__c = productMap.get(className) + account.Username__c;

                    assetList.add(asset);
                }
            }
        }

        List<Account> accountList = new List<Account>();

        if(assetList.size() > 0) {
            insert assetList;

            for(Asset asset : assetList) {
                if(newMap.containsKey(asset.AccountId)) {
                    Account acc = newMap.get(asset.AccountId).clone(true, true, false, false);
                    acc.DefaultClass__c = asset.Id;
                    accountList.add(acc);
                }
            }
        }
        AccountTriggerHandler.disableTrigger();
        update accountList;
        AccountTriggerHandler.enableTrigger();
    }

    public static void createEmptyInventory(List<Account> newRecordList) {

        List<Inventory__c> inventoriesToInsert = new List<Inventory__c>();
        for(Account acc : newRecordList) {
            Inventory__c invent = new Inventory__c(
                Account__c = acc.Id,
                Coins__c = 10
            );
            inventoriesToInsert.add(invent);
        }
        String inventoriesStringified = JSON.serialize(inventoriesToInsert);

        insertInventories(inventoriesStringified);
    }

    @future
    public static void insertInventories(String inventoriesStringified) { //Future method only allows for primitive variables to be sent as parameters
        List<Inventory__c> inventoriesToInsert = (List<Inventory__c>)JSON.deserialize(inventoriesStringified, List<Inventory__c>.class);
        List<InventoryItem__c> itemsToInsert = new List<InventoryItem__c>();

        for(Inventory__c invent : inventoriesToInsert) {
            for(Potion__mdt pot : [SELECT Id, Color__c FROM Potion__mdt]) {
                InventoryItem__c newItem = new InventoryItem__c(
                    Color__c = pot.Color__c,
                    Quantity__c = 0,
                    Inventory__r = invent
                );
                itemsToInsert.add(newItem);
            }
        }

        insert(inventoriesToInsert);
        insert(itemsToInsert);
    }
}