force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Senha usada pelo usuário</description>
    <label>Senha</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username used by the user to login</description>
    <externalId>true</externalId>
    <label>Nome de usuário</label>
    <length>31</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/CurrentChapter__c.field-meta.xml
<CustomField>
    <fullName>CurrentChapter__c</fullName>
    <label>Current Chapter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CurrentPage__c.field-meta.xml
<CustomField>
    <fullName>CurrentPage__c</fullName>
    <label>Current Page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Livro</description>
    <label>Livro</label>
    <nameField>
        <label>Nome do Livro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookCheckpoint__c/BookCheckpoint__c.object-meta.xml
<CustomObject>
    <label>Book Checkpoint</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CheckpointNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Checkpoints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookCheckpoint__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Book</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Book Checkpoints</relationshipLabel>
    <relationshipName>BookCheckpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookCheckpoint__c/fields/Chapter__c.field-meta.xml
<CustomField>
    <fullName>Chapter__c</fullName>
    <label>Chapter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookCheckpoint__c/fields/CurrentPage__c.field-meta.xml
<CustomField>
    <fullName>CurrentPage__c</fullName>
    <label>Current Page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BookCheckpoint__c/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Book.recordType-meta.xml
<RecordType>
    <fullName>Book</fullName>
    <active>true</active>
    <label>Book</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/classes/QuestIntegrationTest.cls
@isTest
private class QuestIntegrationTest {

    @isTest
    static void testGetQuests() {
        // Test data setup
        Account testAccount = new Account(
            Name = 'Test Account',
            Username__c = 'testUsername',
            Password__c = 'Password@123'
        );
        insert testAccount;

        Product2 testProduct = new Product2(
            isActive = true,
            Name = 'Test Asset'
            // Add other required fields
        );
        insert testProduct;

        // Call the REST service
        Test.startTest();
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/quests';
        request.httpMethod = 'GET';
        request.addParameter('username', 'testUsername');
        request.addParameter('recommendation', 'true');

        RestContext.request = request;
        String responseString = QuestIntegration.getAvailableQuests();
        Test.stopTest();

        // Deserialize the response
        QuestIntegration.GetResponse response = (QuestIntegration.GetResponse)JSON.deserialize(responseString, QuestIntegration.GetResponse.class);

        // Assertions
        System.assert(response != null, 'Response should not be null');
        System.assert(response.success, 'Success should be true');
        System.assert(response.quests != null, 'Quests should not be null');
        System.assertEquals(1, response.quests.size(), 'There should be one quest in the response');
        System.assertEquals(testProduct.Id, response.quests[0].id, 'The quest ID should match the test asset ID');
    }

    @isTest
    static void testCreateQuest() {
        // Test data setup
        Account testAccount = new Account(
            Name = 'Test Account',
            Username__c = 'testUsername',
            Password__c = 'Password@123'
        );
        insert testAccount;

        Product2 testProduct = new Product2(
            Name = 'Test Product',
            IsActive = true
            // Add other required fields
        );
        insert testProduct;

        // Call the REST service
        Test.startTest();
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/quests';
        request.httpMethod = 'POST';

        QuestIntegration.PostRequest postRequest = new QuestIntegration.PostRequest();
        postRequest.username = 'testUsername';
        postRequest.id = testProduct.Id;

        request.requestBody = Blob.valueOf(JSON.serialize(postRequest));
        RestContext.request = request;

        String responseString = QuestIntegration.createQuest(postRequest);
        Test.stopTest();

        // Deserialize the response
        QuestIntegration.PostResponse response = (QuestIntegration.PostResponse)JSON.deserialize(responseString, QuestIntegration.PostResponse.class);

        // Assertions
        System.assert(response != null, 'Response should not be null');
        System.assert(response.success, 'Success should be true');
        // Add more assertions based on the expected response
    }

    @isTest
    static void testUpdateQuest() {
        // Test data setup
        Account testAccount = new Account(
            Name = 'Test Account',
            Username__c = 'testUsername',
            Password__c = 'Password@123'
        );
        insert testAccount;

        Product2 testProduct = new Product2(
            Name = 'Test Product',
            IsActive = true,
            RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Book').getRecordTypeId()
            // Add other required fields
        );
        insert testProduct;

        Asset testAsset = new Asset(
            AccountId = testAccount.Id,
            Product2Id = testProduct.Id,
            CurrentChapter__c = 1,
            CurrentPage__c = 5,
            Name = 'Test Product',
            RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Book').getRecordTypeId()
            // Add other required fields
        );
        insert testAsset;

        BookCheckpoint__c testBookCheckpoint = new BookCheckpoint__c(
            Book__c = testProduct.Id,
            Chapter__c = 2,
            Page__c = 5            
            // Add other required fields
        );
        insert testBookCheckpoint;

        // Call the REST service
        Test.startTest();
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/quests';
        request.httpMethod = 'PATCH';

        QuestIntegration.PatchRequest patchRequest = new QuestIntegration.PatchRequest();
        patchRequest.username = 'testUsername';
        patchRequest.id = testAsset.Id;
        patchRequest.currentChapter = 2;

        request.requestBody = Blob.valueOf(JSON.serialize(patchRequest));
        RestContext.request = request;

        String responseString = QuestIntegration.updateQuest(patchRequest);
        Test.stopTest();

        // Deserialize the response
        QuestIntegration.PatchResponse response = (QuestIntegration.PatchResponse)JSON.deserialize(responseString, QuestIntegration.PatchResponse.class);

        // Assertions
        System.assert(response != null, 'Response should not be null');
        System.assert(response.success, 'Success should be true');
        // Add more assertions based on the expected response
    }
}