force-app/main/default/objects/Account/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Username used by the user to login</description>
    <externalId>true</externalId>
    <label>Nome de usuário</label>
    <length>31</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/classes/AssetHelper.cls
public with sharing class AssetHelper {
    public static void createExternalId(List<Asset> newRecordList) {
        Set<Id> accountIdSet = new Set<Id>();
        for(Asset asst : newRecordList) {
            accountIdSet.add(asst.AccountId);
        }
        Map<Id, Account> accountMap = new Map<Id, Account>([SELECT Id, Username__c FROM Account WHERE Id IN: accountIdSet]);
        for(Asset asst : newRecordList) {
            asst.ExternalId__c = (asst.Product2Id + accountMap.get(asst.AccountId).Username__c);
        }
    }
}